spring.application.name=basic-crud-app-one
spring.output.ansi.enabled=always
# Replacing [%15.15t] with [%t] removes left padding
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){faint} %clr(%logger{0}){cyan} %clr(:){faint} %m%n