spring.application.name = basic-crud-app-one
spring.output.ansi.enabled = always
# Replacing [%15.15t] with [%t] removes left padding
logging.pattern.console = %clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){faint} %clr(%logger{0}){cyan} %clr(:){faint} %m%n

# Database configurations
spring.datasource.url = jdbc:mysql://localhost:3306/student_crud_db
spring.datasource.username = root
spring.datasource.password = MySQL@123

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

debug = true